name: Build and deploy to GCP 

on: workflow_dispatch

jobs:
  build-and-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/105380254004/locations/global/workloadIdentityPools/github/providers/prayer-api-repo'
          service_account: 'prayer-api@prayer-404014.iam.gserviceaccount.com'
    
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authorize Docker to Google Container Registry
        run: gcloud auth configure-docker asia-docker.pkg.dev

      - name: Build Container
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: asia-docker.pkg.dev/prayer-404014/asia.gcr.io/prayer-website:${{ github.sha }}
          build-args: |
            VERSION=${{ github.sha }}

      - name: Deploy to GCP Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: prayer-website
          image: asia-docker.pkg.dev/prayer-404014/asia.gcr.io/prayer-website:${{ github.sha }}
          region: asia-northeast1
          env_vars: |
            NODE_ENV=production
            BUCKET_NAME=${{ secrets.BUCKET_NAME }}
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            VERSION=${{ github.sha }}
          secrets: |
            DATABASE_URL=prayer-api-db-url:latest
            DJAGNO_SECRET_KEY=prayer-api-django-secret-key:latest
          flags: '--add-cloudsql-instances=${{ secrets.CLOUDSQL_INSTANCE_ID }}'
